# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
# Global settings
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - test
    - open_index.json
    - .idea

# Site settings
title      : Vespa
email      : ""
description: ""
baseurl    : ""
url        : ""
defaults:
    -
        scope:
            path  : ""
        values:
            layout: "default"
            index : true

search:
    namespace: "open"
    endpoint : "https://vespa-documentation-search.vespa.global.vespa.oath.cloud"
    do_feed  : true
    do_index_removal_before_feed: false
    feed_endpoints:
        - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.z.vespa-app.cloud/
          indexes:
              - open_index.json
        - url: https://vespacloud-docsearch.vespa-team.aws-ap-northeast-1a.z.vespa-app.cloud/
          indexes:
              - open_index.json

# Build settings
markdown: kramdown
