shared:
  settings:
    email:
      addresses: [kraune@verizonmedia.com]
      statuses: [SUCCESS, FAILURE]

jobs:
  link-checker-documentation:
    requires: [~pr, ~commit]
    image: ruby:2.6
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/buildPeriodically: H 0 * * *
    steps:
      - install-deps: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          bundle exec htmlproofer \
            --assume-extension --empty_alt_ignore \
            --typhoeus-config '{"connecttimeout": 10, "timeout": 30}' \
            _site

  verify-guides:
    requires: [~commit]
    secrets:
      - VESPA_TEAM_API_KEY
    image: vespaengine/vespa-pipeline
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
    steps:
      - install-deps: |
          source /etc/profile.d/jdk-env.sh
          yum install -y python36-pip
          pip3 install -qqq --upgrade pip
          pip3 install -qqq -r test/requirements.txt --user
          yum install -y openssl
          yum install -y yum-utils
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install -y docker-ce docker-ce-cli containerd.io
      - run-tests: |
          export VESPA_TEAM_API_KEY
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config.yml
